services:
  balancer:
    image: nginx:mainline-alpine3.21
    restart: unless-stopped
    labels:
      - dev.orbstack.domains=web.orb.local
    volumes:
      - ./web:/var/www/web
      - ./config/balancer:/etc/nginx/templates
  
  websocket:
    image: centrifugo/centrifugo:v6.1
    restart: unless-stopped
    command: centrifugo -c config.json
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./config/websocket/config.json:/centrifugo/config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535