services:
  database:
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready",
        "-d",
        "$DB_NAME"
      ]
      retries: 10
      interval: 5s
      timeout: 5s
      start_period: 80s

  migration-service:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      database:
        condition: service_healthy
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://$DB_USER:$DB_PASS@database/$DB_NAME?sslmode=disable",
      "goto",
      "$DB_VERSION"
    ]

volumes:
  database-data: